package GUI;

import HOLICOP.Employe;
import HOLICOP.Voyageur;
import Thread.ThreadReception;
import java.io.IOException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

public class Chat extends javax.swing.JFrame
{
    private String username;
    private String adresse;
    private String personne;
    
    private int port;
    
    Voyageur voy;
    Employe emp;
    ThreadReception thr;
    
    Login l;
    
    public Chat()
    {
        initComponents();
        login();
        setTitle(personne + " " + username);
        DefaultListModel dlm = new DefaultListModel();
        listChat.setModel(dlm);
        
        if(personne.equals("Voyageur"))
        {
            checkBoxQuestion.setEnabled(true);
            voy = new Voyageur(username, adresse, port);
            thr = new ThreadReception(username, true, voy.getSocketGroupe(), listChat, null); //true car voyageur
            thr.start();
            String msgDeb = voy.getIdentifiant() + " rejoint le groupe";
            voy.post_Event(msgDeb);
        }
        else
        {
            comboBoxQuestion.setEnabled(true);
            emp = new Employe(username, adresse, port);
            thr = new ThreadReception(username, false, emp.getSocketGroupe(), listChat, comboBoxQuestion); //false car employé
            thr.start();
            String msgDeb = emp.getIdentifiant() + " rejoint le groupe";
            emp.post_Event(msgDeb);
        }
    }
    
    private void login()
    {
        l = new Login(this, true);

        l.setVisible(true);
        if(!l.isDisplayable()) //si clic sur croix
            System.exit(0);

        username = l.getUsername();
        port = l.getPort();
        adresse = l.getAdresse();
        personne = l.getPersonne();
        labelPersonne.setText(personne + " " + username);
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane1 = new javax.swing.JScrollPane();
        listChat = new javax.swing.JList<>();
        labelPersonne = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fieldMessage = new javax.swing.JTextField();
        buttonSend = new javax.swing.JButton();
        checkBoxQuestion = new javax.swing.JCheckBox();
        comboBoxQuestion = new javax.swing.JComboBox<>();
        buttonLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(listChat);

        labelPersonne.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelPersonne.setText("Personne");

        jLabel2.setText("Message:");

        buttonSend.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        buttonSend.setText("Send");
        buttonSend.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonSendActionPerformed(evt);
            }
        });

        checkBoxQuestion.setText("Question");
        checkBoxQuestion.setEnabled(false);

        comboBoxQuestion.setEnabled(false);

        buttonLogout.setText("Se déconnecter");
        buttonLogout.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldMessage))
                    .addComponent(buttonSend, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelPersonne)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonLogout))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(checkBoxQuestion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboBoxQuestion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelPersonne)
                    .addComponent(buttonLogout))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkBoxQuestion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fieldMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonSend, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSendActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buttonSendActionPerformed
    {//GEN-HEADEREND:event_buttonSendActionPerformed
        if(!fieldMessage.getText().equals(""))
        {
            if(personne.equals("Voyageur"))
            {
                String msg = username + "> " + fieldMessage.getText();
                if(!checkBoxQuestion.isSelected())
                    voy.post_Event(msg);
                else
                    voy.post_Question(msg);
            }
            else
            {
                DefaultComboBoxModel dcbm = (DefaultComboBoxModel) comboBoxQuestion.getModel();
                if(dcbm.getSelectedItem().equals("Post Event"))
                {
                    String msg = username + "> " + fieldMessage.getText();
                    emp.post_Event(msg);
                }
                else
                {
                    String msg = comboBoxQuestion.getSelectedItem()+ "@" + username + "> " + fieldMessage.getText();
                    emp.answer_Question(msg);      
                }
            }
        }
    }//GEN-LAST:event_buttonSendActionPerformed

    private void buttonLogoutActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buttonLogoutActionPerformed
    {//GEN-HEADEREND:event_buttonLogoutActionPerformed
        String msg;
        
        if(l.getCliSock() == null || l.getCliSock().isClosed())
            return;
        try
        {
            if(personne.equals("Voyageur"))
            {
                msg = voy.getIdentifiant() + " quitte le groupe";
                voy.post_Event(msg);
            }
            else
            {
                msg = emp.getIdentifiant() + " quitte le groupe";
                emp.post_Event(msg);
            }
            
            l.getOos().close();
            l.getOis().close();
            l.getCliSock().close();
            System.exit(0);
        } 
        catch (IOException ex) 
        {
            JOptionPane.showMessageDialog(rootPane, "Exception: " + ex.getMessage());
        }
    }//GEN-LAST:event_buttonLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Chat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonLogout;
    private javax.swing.JButton buttonSend;
    private javax.swing.JCheckBox checkBoxQuestion;
    private javax.swing.JComboBox<String> comboBoxQuestion;
    private javax.swing.JTextField fieldMessage;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelPersonne;
    private javax.swing.JList<String> listChat;
    // End of variables declaration//GEN-END:variables
}
