/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Message.*;
import Reponse.ReponseFUCAMP;
import Requete.RequeteFUCAMP;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 *
 * @author Mika
 */
public class CliForm extends javax.swing.JFrame
{
    int port;
    String username;
    Socket socket;
    private ObjectOutputStream oos;
    private ObjectInputStream ois;
    
    /**
     * Creates new form CliForm
     */
    public CliForm()
    {
        initComponents();
    }
    
    public CliForm(String portProp)
    {
        initComponents();
        setTitle("Client Activités");
        port = Integer.parseInt(portProp);
        
        login();
        buildJList(this);
    }
    
    private void login()
    {
        boolean authenticated = false;
        Login l = new Login(this, true);
        String username, password;
        try
        {
            while(!authenticated)
            {
                l.setVisible(true);
                if(!l.isDisplayable()) //si clic sur croix
                    System.exit(0);
                username = l.getUsername();
                password = l.getPassword();

                //System.out.println("CliForm " + username + " " + password);
                socket = new Socket("127.0.0.1", port);
                oos = new ObjectOutputStream(socket.getOutputStream());
                ois = new ObjectInputStream(socket.getInputStream());

                RequeteFUCAMP req = new RequeteFUCAMP(RequeteFUCAMP.REQUEST_LOGIN, new MessageLogin(username, password));
                oos.writeObject(req); //on stocke la requete login sur le flux output

                ReponseFUCAMP rep = (ReponseFUCAMP)ois.readObject(); //on récupère la réponse du flux input
                if(rep.getCode() == ReponseFUCAMP.SUCCESS)
                {
                    JOptionPane.showMessageDialog(rootPane, ((MessageSimple)rep.getMessage()).getMessage()); //affiche message succès
                    labelWelcome.setText("Bonjour " + username + "!");
                    break;
                }
                
                JOptionPane.showMessageDialog(rootPane, ((MessageSimple)rep.getMessage()).getMessage()); //affiche message d'erreur
                oos.close();
                ois.close();
                socket.close();
            }
        }
        catch (IOException | ClassNotFoundException ex) 
        {
            Logger.getLogger(CliForm.class.getName()).log(Level.SEVERE, null, ex);
            return;
        }
    }
    
    private void buildJList(CliForm aThis)
    {
        DefaultListModel dlm = new DefaultListModel();
        dlm.addElement("Ski 3 jours"); dlm.addElement("Plongée 1 jour"); dlm.addElement("Promenade 1 jour"); dlm.addElement("Camping 2 jours");
        listActivites.setModel(dlm);
        
        //pour la détection d'un double clic
        listActivites.addMouseListener(new MouseAdapter() 
        {
            public void mouseClicked(MouseEvent evt) 
            {
                JList list = (JList)evt.getSource();
                if(evt.getClickCount() == 2) 
                {
                    System.out.println(listActivites.getSelectedValue());
                } 
            }
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        labelWelcome = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listActivites = new javax.swing.JList<>();
        buttonLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelWelcome.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelWelcome.setText("labelWelcome");

        jScrollPane1.setViewportView(listActivites);

        buttonLogout.setText("Logout");
        buttonLogout.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelWelcome)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonLogout))
                .addContainerGap(225, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelWelcome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addComponent(buttonLogout)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonLogoutActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buttonLogoutActionPerformed
    {//GEN-HEADEREND:event_buttonLogoutActionPerformed
        if(socket==null || socket.isClosed())
                return;
        try
        {
            oos.writeObject(new RequeteFUCAMP(RequeteFUCAMP.REQUEST_LOGOUT));
            ReponseFUCAMP rep = (ReponseFUCAMP) ois.readObject();
            
            if(rep.getCode() == ReponseFUCAMP.SUCCESS)
                JOptionPane.showMessageDialog(rootPane, ((MessageSimple)rep.getMessage()).getMessage());
            
            oos.close();
            ois.close();
            socket.close();
            System.exit(0);
        } 
        catch (IOException ex) 
        {
            Logger.getLogger(CliForm.class.getName()).log(Level.SEVERE, null, ex);
        } 
        catch (ClassNotFoundException ex) 
        {
            Logger.getLogger(CliForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(CliForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(CliForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(CliForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(CliForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new CliForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonLogout;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelWelcome;
    private javax.swing.JList<String> listActivites;
    // End of variables declaration//GEN-END:variables
}
